### ISSUE TITLE
Getting this error -> argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Abutahir12** [swarajjena/apidoc-swagger-converter#1]
Am I doing anything wrong here? I have a file called doc.js in the folder named `InputData` and the output folder is named `swagger`

This is the traceback
```
D:\personal>apidoc-swagger-converter -i InputData\doc.js -o swagger 
try add hooks
{"level":"error","message":"The \"path\" argument must be of type string. Received undefined"}
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at main (C:\Users\91805\AppData\Roaming\npm\node_modules\apidoc-swagger-converter\lib.js:49:31)
    at Object.<anonymous> (C:\Users\91805\AppData\Roaming\npm\node_modules\apidoc-swagger-converter\bin.js:117:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0

**Comment by tsmanuelanton** [comment]
Hello, same problem here. Any solutions?
